const insertPolishesSQLString = `INSERT INTO polishes (polishName, polishFormula, releaseDate, retired, limitedEdition, collectionName)
VALUES
('One-Coat Black', NULL, '2019-07-06', FALSE, FALSE, 'Holo Taco Launch Collection'),
('Royal-Tea Blue', NULL, '2019-07-06', FALSE, FALSE, 'Holo Taco Launch Collection'),
('Flakie Holo Taco', NULL, '2019-07-06', FALSE, FALSE, 'Holo Taco Launch Collection'),
('Scattered Holo Taco', NULL, '2019-07-06', FALSE, FALSE, 'Holo Taco Launch Collection'),
('Linear Holo Taco', NULL, '2019-07-06', FALSE, FALSE, 'Holo Taco Launch Collection'),
('Play Rosé', NULL, '2019-11-16', FALSE, FALSE, 'Holo Taco Holoday Collection'),
('Midnight Spark', NULL, '2019-11-16', FALSE, FALSE, 'Holo Taco Holoday Collection'),
('Party Punch', NULL, '2019-11-16', FALSE, FALSE, 'Holo Taco Holoday Collection'),
('Frost Light', NULL, '2019-11-16', TRUE, FALSE, 'Holo Taco Holoday Collection'),
('Rainbow Snow', NULL, '2019-11-16', FALSE, FALSE, 'Holo Taco Holoday Collection'),
('Not Milky White', NULL, '2020-03-15', FALSE, FALSE, 'Holo Taco Unicorn Skin Collection'),
('Indigo Away', NULL, '2020-03-15', FALSE, FALSE, 'Holo Taco Unicorn Skin Collection'),
('Cosmic Unicorn Skin', NULL, '2020-03-15', FALSE, FALSE, 'Holo Taco Unicorn Skin Collection'),
('Aurora Unicorn Skin', NULL, '2020-03-15', FALSE, FALSE, 'Holo Taco Unicorn Skin Collection'),
('Solar Unicorn Skin', NULL, '2020-03-15', FALSE, FALSE, 'Holo Taco Unicorn Skin Collection'),
('Green Taffy', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Blue Freezie', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Purple Slushie', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Magenta Jelly', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Red Licorice', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Orange Drink', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Lemon Sucker', NULL, '2020-06-13', FALSE, FALSE, 'Holo Taco Rainbow Collection'),
('Gold Flakie Holo Taco', NULL, '2020-07-18', TRUE, FALSE, 'Holo Taco 1st Anniversary Collection'),
('Purple Flakie Holo Taco', NULL, '2020-07-18', TRUE, FALSE, 'Holo Taco 1st Anniversary Collection'),
('Blue Flakie Holo Taco', NULL, '2020-07-18', TRUE, FALSE, 'Holo Taco 1st Anniversary Collection'),
('Menchie The Cat', NULL, '2020-08-22', FALSE, FALSE, 'Holo Taco Menchie & Zyler Duo'),
('Zyler The Cat', NULL, '2020-08-22', FALSE, FALSE, 'Holo Taco Menchie & Zyler Duo'),
('Cats'' Evasion', NULL, '2020-09-26', FALSE, FALSE, 'Holo Taco Multichrome Collection'),
('Purple With Envy', NULL, '2020-09-26', FALSE, FALSE, 'Holo Taco Multichrome Collection'),
('Blue Ain''t Slick', NULL, '2020-09-26', TRUE, FALSE, 'Holo Taco Multichrome Collection'),
('Chameleon Coat', NULL, '2020-09-26', TRUE, FALSE, 'Holo Taco Multichrome Collection'),
('Missed-Shift', NULL, '2020-09-26', FALSE, FALSE, 'Holo Taco Multichrome Collection'),
('Got Cake?', NULL, '2020-10-17', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2020'),
('Gift Receipt', NULL, '2020-11-07', FALSE, FALSE, 'Holo Taco Frosted Metals Collection'),
('Cold Shoulder', NULL, '2020-11-07', TRUE, FALSE, 'Holo Taco Frosted Metals Collection'),
('Cheap Champagne', NULL, '2020-11-07', FALSE, FALSE, 'Holo Taco Frosted Metals Collection'),
('Mint Money', NULL, '2020-11-07', FALSE, FALSE, 'Holo Taco Frosted Metals Collection'),
('Fake Date', NULL, '2020-11-07', TRUE, FALSE, 'Holo Taco Frosted Metals Collection'),
('What Do You Pink?', NULL, '2021-02-27', FALSE, FALSE, 'Holo Taco Unicorn Dream Collection'),
('Cyantific', NULL, '2021-02-27', FALSE, FALSE, 'Holo Taco Unicorn Dream Collection'),
('Galactic Unicorn Skin', NULL, '2021-02-27', FALSE, FALSE, 'Holo Taco Unicorn Dream Collection'),
('Sonic Unicorn Skin', NULL, '2021-02-27', FALSE, FALSE, 'Holo Taco Unicorn Dream Collection'),
('Lunar Unicorn Skin', NULL, '2021-02-27', FALSE, FALSE, 'Holo Taco Unicorn Dream Collection'),
('Green Screen', NULL, '2021-03-20', FALSE, FALSE, 'For Art''s Sake Bundle'),
('Banana Hacks', NULL, '2021-03-20', TRUE, FALSE, 'For Art''s Sake Bundle'),
('Duct Tape Grey', NULL, '2021-03-20', FALSE, FALSE, 'For Art''s Sake Bundle'),
('Lemon Spritzer', NULL, '2021-04-17', TRUE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Peach Tea', NULL, '2021-04-17', FALSE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Coral Chaser', NULL, '2021-04-17', FALSE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Pink Fizz', NULL, '2021-04-17', FALSE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Lavender Syrup', NULL, '2021-04-17', FALSE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Sparkling Water', NULL, '2021-04-17', FALSE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Mint Mojito', NULL, '2021-04-17', FALSE, FALSE, 'Holo Taco Pastel Rainbow Collection'),
('Full Charge', NULL, '2021-06-05', TRUE, FALSE, 'Holo Taco Electric Holos Collection'),
('Hydropower', NULL, '2021-06-05', FALSE, FALSE, 'Holo Taco Electric Holos Collection'),
('Hot-Wire Pink', NULL, '2021-06-05', FALSE, FALSE, 'Holo Taco Electric Holos Collection'),
('Electrostatic', NULL, '2021-06-05', FALSE, FALSE, 'Holo Taco Electric Holos Collection'),
('Circuit Breaker', NULL, '2021-06-05', FALSE, FALSE, 'Holo Taco Electric Holos Collection'),
('The Floor Is Guava', NULL, '2021-06-29', FALSE, FALSE, 'Life''s A Beach Bundle'),
('One Melon Followers', NULL, '2021-06-29', TRUE, FALSE, 'Life''s A Beach Bundle'),
('Sea Foam Home', NULL, '2021-06-29', TRUE, FALSE, 'Life''s A Beach Bundle'),
('Glitterally Purple', NULL, '2021-07-31', TRUE, FALSE, '2nd Anniversary Holo Taco Remix Collection'),
('Everything Taco', NULL, '2021-07-31', FALSE, FALSE, '2nd Anniversary Holo Taco Remix Collection'),
('Way-Back Chrome', NULL, '2021-07-31', TRUE, FALSE, '2nd Anniversary Holo Taco Remix Collection'),
('Heavy Metal Mixtape', NULL, '2021-07-31', TRUE, FALSE, '2nd Anniversary Holo Taco Remix Collection'),
('Rainbow Flood', NULL, '2021-07-31', TRUE, FALSE, '2nd Anniversary Holo Taco Remix Collection'),
('Gold Flake Taco', NULL, '2021-09-18', FALSE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('I''m Over Brew', NULL, '2021-09-18', FALSE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('Butterscotch Hop', NULL, '2021-09-18', FALSE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('High Tea Hibiscus', NULL, '2021-09-18', FALSE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('Bring Me The Teal', NULL, '2021-09-18', FALSE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('Matcha Maker', NULL, '2021-09-18', TRUE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('See Y''all Later Chai', NULL, '2021-09-18', FALSE, FALSE, 'Holo Taco Tea Crèmes Collection'),
('Existential Crisis', NULL, '2021-10-16', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2021'),
('Frozen Benanas', NULL, '2021-10-16', TRUE, FALSE, 'Simply''s Birthday Nail Polish 2021 Release'),
('Naughty List', NULL, '2021-11-13', TRUE, FALSE, 'Holo Taco Cristmas Collection'),
('Plumb Luck', NULL, '2021-11-13', TRUE, FALSE, 'Holo Taco Cristmas Collection'),
('Gold Play Button', NULL, '2021-11-13', TRUE, FALSE, 'Holo Taco Cristmas Collection'),
('Everything Is Pine', NULL, '2021-11-13', TRUE, FALSE, 'Holo Taco Cristmas Collection'),
('Choco-Holo', NULL, '2021-11-13', TRUE, FALSE, 'Holo Taco Cristmas Collection'),
('Black Holo Wish', NULL, '2021-11-13', TRUE, FALSE, 'Holo Taco Cristmas Collection'),
('Shady Navy', NULL, '2022-01-22', FALSE, FALSE, 'Holo Taco Winter Shimmers Collection'),
('Laven-Duh', NULL, '2022-01-22', TRUE, FALSE, 'Holo Taco Winter Shimmers Collection'),
('Twilight Shimmer', NULL, '2022-01-22', FALSE, FALSE, 'Holo Taco Winter Shimmers Collection'),
('Polar Princess', NULL, '2022-01-22', FALSE, FALSE, 'Holo Taco Winter Shimmers Collection'),
('Celestial Lights', NULL, '2022-01-22', FALSE, FALSE, 'Holo Taco Winter Shimmers Collection'),
('Bored Meeting', NULL, '2022-02-28', FALSE, FALSE, 'Work/Life Balance Bundle'),
('Left On Red', NULL, '2022-02-28', FALSE, FALSE, 'Work/Life Balance Bundle'),
('Here For The Payday', NULL, '2022-02-28', TRUE, FALSE, 'Work/Life Balance Bundle'),
('Work Bestie', NULL, '2022-02-28', FALSE, FALSE, 'Work/Life Balance Bundle'),
('Lite Link', NULL, '2022-04-02', FALSE, FALSE, 'Holo Taco Lite Mode Collection'),
('Wireless Mode', NULL, '2022-04-02', FALSE, FALSE, 'Holo Taco Lite Mode Collection'),
('Flash Drive', NULL, '2022-04-02', FALSE, FALSE, 'Holo Taco Lite Mode Collection'),
('Encryption Key', NULL, '2022-04-02', TRUE, FALSE, 'Holo Taco Lite Mode Collection'),
('Sunset Simulation', NULL, '2022-04-02', FALSE, FALSE, 'Holo Taco Lite Mode Collection'),
('Magical Mustache', NULL, '2022-06-03', TRUE, FALSE, 'Holo Taco x Julien Collection'),
('I''m Live', NULL, '2022-06-03', TRUE, FALSE, 'Holo Taco x Julien Collection'),
('Bep Bep Blue', NULL, '2022-06-03', TRUE, FALSE, 'Holo Taco x Julien Collection'),
('Greyt', NULL, '2022-06-03', TRUE, FALSE, 'Holo Taco x Julien Collection'),
('Monstera', NULL, '2022-06-03', TRUE, FALSE, 'Holo Taco x Julien Collection'),
('Reflective Taco', NULL, '2022-07-16', FALSE, FALSE, '3rd Anniversary Gala Collection'),
('Featured Guest', NULL, '2022-07-16', FALSE, FALSE, '3rd Anniversary Gala Collection'),
('Highest Bidder', NULL, '2022-07-16', TRUE, FALSE, '3rd Anniversary Gala Collection'),
('Smokeshow', NULL, '2022-07-16', TRUE, FALSE, '3rd Anniversary Gala Collection'),
('Blacklisted', NULL, '2022-07-16', TRUE, FALSE, '3rd Anniversary Gala Collection'),
('Party Of One Purple', NULL, '2022-07-16', FALSE, FALSE, '3rd Anniversary Gala Collection'),
('Crimson Void', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Burnt Bridges', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Amber Apathy', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Lost In The Woods', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Sunken Secrets', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Violet Nightmares', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Dead Petals', NULL, '2022-09-03', FALSE, FALSE, 'Holo Taco Dark Rainbow Collection'),
('Double Dare', NULL, '2022-10-08', TRUE, FALSE, 'Simply''s Birthday Nail Polish 2022'),
('Favourite Sister', NULL, '2022-10-08', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2022 Release'),
('Oh My Gourd', NULL, '2022-10-08', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2022 Release'),
('Resting Witch Face', NULL, '2022-10-08', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2022 Release'),
('Glow In The Dark Taco', NULL, '2022-10-08', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2022 Release'),
('Love Spell', NULL, '2022-11-19', FALSE, FALSE, 'Holo Taco Magnetic Magic Collection'),
('Queen''s Curse', NULL, '2022-11-19', TRUE, FALSE, 'Holo Taco Magnetic Magic Collection'),
('Twice In A Blue Moon', NULL, '2022-11-19', FALSE, FALSE, 'Holo Taco Magnetic Magic Collection'),
('Wicked Potion', NULL, '2022-11-19', FALSE, FALSE, 'Holo Taco Magnetic Magic Collection'),
('Fairy Tail', NULL, '2022-11-19', TRUE, FALSE, 'Holo Taco Magnetic Magic Collection'),
('Silver Flake Taco', NULL, '2022-12-06', FALSE, FALSE, '12 Days of Cristmas Release'),
('Red Flake Taco', NULL, '2022-12-06', FALSE, FALSE, '12 Days of Cristmas Release'),
('Oat Couture', NULL, '2023-01-18', FALSE, FALSE, 'Holo Barista Bundle'),
('Blushed Ice', NULL, '2023-01-18', FALSE, FALSE, 'Holo Barista Bundle'),
('Holo Cappuccino', NULL, '2023-01-18', FALSE, FALSE, 'Holo Barista Bundle'),
('Need I Say Mocha?', NULL, '2023-01-18', FALSE, FALSE, 'Holo Barista Bundle'),
('Espresso Your Holo', NULL, '2023-01-18', FALSE, FALSE, 'Holo Barista Bundle'),
('World''s First', NULL, '2023-02-25', FALSE, FALSE, 'Holo Taco One-Coat Chrome Collection'),
('Trophy Life', NULL, '2023-02-25', FALSE, FALSE, 'Holo Taco One-Coat Chrome Collection'),
('Pink Steel', NULL, '2023-02-25', FALSE, FALSE, 'Holo Taco One-Coat Chrome Collection'),
('Iron Violet', NULL, '2023-02-25', FALSE, FALSE, 'Holo Taco One-Coat Chrome Collection'),
('Aquafoil', NULL, '2023-02-25', TRUE, FALSE, 'Holo Taco One-Coat Chrome Collection'),
('Pinky Swear', NULL, '2023-03-22', FALSE, FALSE, 'Pastel & Don''t Tell Bundle'),
('Rest In Peach', NULL, '2023-03-22', FALSE, FALSE, 'Pastel & Don''t Tell Bundle'),
('Banana Medicine', NULL, '2023-03-22', FALSE, FALSE, 'Pastel & Don''t Tell Bundle'),
('Crime And Punishmint', NULL, '2023-03-22', FALSE, FALSE, 'Pastel & Don''t Tell Bundle'),
('Too Good To Be Blue', NULL, '2023-03-22', FALSE, FALSE, 'Pastel & Don''t Tell Bundle'),
('Cereal Killer', NULL, '2023-03-22', FALSE, FALSE, 'Pastel & Don''t Tell Bundle'),
('Toe Beans', NULL, '2023-04-15', TRUE, FALSE, 'Holo Royalty Debut Trio'),
('Glamethyst', NULL, '2023-04-15', TRUE, FALSE, 'Holo Royalty Debut Trio'),
('Royal Crush', NULL, '2023-04-15', TRUE, FALSE, 'Holo Royalty Debut Trio'),
('Never Tide Down', NULL, '2023-05-20', FALSE, FALSE, 'Holo Taco Vacation Collection'),
('Tax Haven', NULL, '2023-05-20', FALSE, FALSE, 'Holo Taco Vacation Collection'),
('Private Villa', NULL, '2023-05-20', FALSE, FALSE, 'Holo Taco Vacation Collection'),
('Beach Please', NULL, '2023-05-20', FALSE, FALSE, 'Holo Taco Vacation Collection'),
('Late Checkout', NULL, '2023-05-20', FALSE, FALSE, 'Holo Taco Vacation Collection'),
('Cold Slate', NULL, '2023-06-16', FALSE, FALSE, 'Fire & Ice Bundle'),
('Hot Take', NULL, '2023-06-16', FALSE, FALSE, 'Fire & Ice Bundle'),
('Scorched Earth', NULL, '2023-06-16', FALSE, FALSE, 'Fire & Ice Bundle'),
('Halogen Glow', NULL, '2023-06-16', FALSE, FALSE, 'Fire & Ice Bundle'),
('Freezer Burn', NULL, '2023-06-16', FALSE, FALSE, 'Fire & Ice Bundle'),
('Be Kind Rewind', NULL, '2023-07-22', TRUE, FALSE, '4th Anniversary Holo Taco Retro Collection'),
('Life In Plastic', NULL, '2023-07-22', TRUE, FALSE, '4th Anniversary Holo Taco Retro Collection'),
('Hi-Def', NULL, '2023-07-22', TRUE, FALSE, '4th Anniversary Holo Taco Retro Collection'),
('Anti-Hero', NULL, '2023-07-22', TRUE, FALSE, '4th Anniversary Holo Taco Retro Collection'),
('Box Office Bomb', NULL, '2023-07-22', TRUE, FALSE, '4th Anniversary Holo Taco Retro Collection'),
('Not Pressed', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Modest Moss', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Nightshade', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Stay Grounded', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Lowkey Blushing', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Brick Wall', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Fallen Flake Taco', NULL, '2023-08-16', FALSE, FALSE, 'Down to Earth Bundle'),
('Spirit Fingers', NULL, '2023-09-09', TRUE, FALSE, 'Holo Taco x Safiya Collection'),
('Bat B*tch', NULL, '2023-09-09', TRUE, FALSE, 'Holo Taco x Safiya Collection'),
('Feeling Fiendish', NULL, '2023-09-09', TRUE, FALSE, 'Holo Taco x Safiya Collection'),
('Brucie', NULL, '2023-09-09', TRUE, FALSE, 'Holo Taco x Safiya Collection'),
('Berry Me In Holo', NULL, '2023-09-09', TRUE, FALSE, 'Holo Taco x Safiya Collection'),
('Cracked Taco Shell', NULL, '2023-10-02', FALSE, FALSE, 'Rest In Pieces Bundle'),
('Zyler Cat Eye', NULL, '2023-10-14', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2023'),
('Menchie Cat Eye', NULL, '2023-10-14', FALSE, FALSE, 'Simply''s Birthday Nail Polish 2023'),
('Cool Cat Mom', NULL, '2023-10-14', TRUE, FALSE, 'Simply''s Birthday Nail Polish 2023'),
('Curfew Crasher', NULL, '2023-11-11', FALSE, FALSE, 'After Party Collection'),
('Crystal Skies', NULL, '2023-11-11', FALSE, FALSE, 'After Party Collection'),
('Starry-Eyed', NULL, '2023-11-11', FALSE, FALSE, 'After Party Collection'),
('Bottle Service', NULL, '2023-11-11', FALSE, FALSE, 'After Party Collection'),
('Midnight Owl', NULL, '2023-11-11', FALSE, FALSE, 'After Party Collection'),
('Disco Dust Taco', NULL, '2023-11-11', FALSE, FALSE, 'After Party Collection'),
('Fifty Shades of Greige', NULL, '2023-12-01', FALSE, FALSE, 'Declassified Tacos Set [001]'),
('Sacrificial Lacquer', NULL, '2023-12-01', FALSE, FALSE, 'Declassified Tacos Set [001]'),
('Overshadowed', NULL, '2023-12-01', FALSE, FALSE, 'Declassified Tacos Set [001]'),
('Foiled Again', NULL, '2023-12-01', FALSE, FALSE, 'Declassified Tacos Set [001]'),
('Rose Gold Flake Taco', NULL, '2023-12-01', FALSE, FALSE, 'Declassified Tacos Set [001]'),
('Orbite Me', NULL, '2024-02-10', FALSE, FALSE, 'I Need Space Collection'),
('I''m Rover It', NULL, '2024-02-10', FALSE, FALSE, 'I Need Space Collection'),
('Waste Of Space', NULL, '2024-02-10', FALSE, FALSE, 'I Need Space Collection'),
('Alien Infatuation', NULL, '2024-02-10', FALSE, FALSE, 'I Need Space Collection'),
('Solo Mission', NULL, '2024-02-10', FALSE, FALSE, 'I Need Space Collection'),
('Milky White Shimmer', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Black Flake Taco', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Peri-Social', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Sweet Tooth', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Butter Me Up', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Ginger Snatched', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Brownie Points', NULL, '2024-03-20', FALSE, FALSE, 'Cookies & Crèmes Bundle'),
('Teal No Lies', NULL, '2024-04-20', FALSE, TRUE, 'Holo Royalty Shimmering Secrets Set'),
('Blush Money', NULL, '2024-04-20', FALSE, TRUE, 'Holo Royalty Shimmering Secrets Set'),
('Spyglass', NULL, '2024-04-20', FALSE, TRUE, 'Holo Royalty Shimmering Secrets Set'),
('Inside Job', NULL, '2024-04-20', FALSE, TRUE, 'Holo Royalty Shimmering Secrets Set'),
('Electric Sweetener', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Pop Rocker', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Jam Session', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Sunshine Crush', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Sour Note', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Blue Rizzler', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Sugar Rush', NULL, '2024-05-25', FALSE, FALSE, 'Rock Candy Collection'),
('Funny Feeling', NULL, '2024-07-13', FALSE, TRUE, '5th Anniversary Holo Taco Mixed Emotions Collection'),
('Rage Bait', NULL, '2024-07-13', FALSE, TRUE, '5th Anniversary Holo Taco Mixed Emotions Collection'),
('Guilty Pleasure', NULL, '2024-07-13', FALSE, TRUE, '5th Anniversary Holo Taco Mixed Emotions Collection'),
('Deeply Superficial', NULL, '2024-07-13', FALSE, TRUE, '5th Anniversary Holo Taco Mixed Emotions Collection'),
('Simply Chaotic', NULL, '2024-07-13', FALSE, TRUE, '5th Anniversary Holo Taco Mixed Emotions Collection'),
('Head Hunter', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Foreshadow', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Ivory Tower', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Devil''s Advocate', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Secret Society', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Silent Library', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Ivy League', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Inkwell', NULL, '2024-09-04', FALSE, FALSE, 'Dark Academia Collection'),
('Gosh Garnet', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Crystal Mommy', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Happily Ever Aqua', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Ride Or Diamond', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Emerald City', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('The Price Is Alexandrite', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Ruby, Madly, Deeply', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Peridon''t Bother Me', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Playing With Sapphire', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Birthday Brat', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Topaz Tears', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection'),
('Tanzanite Away', NULL, '2024-10-12', FALSE, FALSE, 'Birthstone Collection');`